### ISSUE TITLE
Basis.MONOMIAL should be Basis.LAGRANGE

### ISSUE THREAD

**Issue by franklynwang** [0xPARC/plonkathon#3]
https://github.com/0xPARC/plonkathon/blob/cea88fd7b2fe99f21ea50d1444444565cb777e00/poly.py#L161-L163

Basis.LAGRANGE should be replaced for Basis.MONOMIAL here, as well as including FFT. All-in-all, 

```
return Polynomial(
            [v * inv_offset**i for (i, v) in enumerate(shifted_coeffs)],
            Basis.LAGRANGE,
 )
```

should be replaced by

```
return Polynomial(
            [v * inv_offset**i for (i, v) in enumerate(shifted_coeffs)],
            Basis.MONOMIAL,
 ).fft()

```

**Comment by therealyingtong** [comment]
We don't need the `.fft()` because we want to return a polynomial in the coefficient form (i.e. monomial basis).
